# Generated by Django 4.2.28 on 2026-02-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_proof',
            new_name='proof',
        ),
    ]
